const { boot, check, tick, summary } = require('./harness');
const U = { uid: 'u1', email: 'ana@example.com', displayName: 'Ana Lima', emailVerified: true };
const IMG = 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAP//////////////////////////////////////////////////////////////////////////////////////wgALCAABAAEBAREA/8QAFBABAAAAAAAAAAAAAAAAAAAAAP/aAAgBAQABPxA=';
const iso = (n) => new Date(Date.now() + n * 86400000).toISOString();
const seed = (d) => {
  d.species.s1 = { name: 'Jiboia', scientific: 'Epipremnum aureum', ownerId: 'u1', waterDays: 3, light: 'Meia-sombra', petToxicity: 'Tóxica', category: 'Trepadeira', icon: '🌿' };
  d.vases.v1 = { speciesId: 's1', ownerId: 'u1', name: 'Vaso da sala', lastWater: iso(-4), history: [{ type: 'lastWater', date: iso(-4) }], photoHistory: [{ photo: IMG, date: iso(-30) }, { photo: IMG + 'B', date: iso(-2) }] };
  d.vases.v2 = { speciesId: 's1', ownerId: 'u1', name: 'Sem fotos', history: [] };
};
const readBlob = (w, blob) => new Promise((res, rej) => { const r = new w.FileReader(); r.onload = () => res(r.result); r.onerror = rej; r.readAsText(blob); });
(async () => {
  const t = await boot({ user: U, seed, pushUrl: 'https://push.test/' });
  const { window: w, document: doc, fb, app } = t;
  const g = (id) => doc.getElementById(id);
  const downloads = [];
  w.HTMLAnchorElement.prototype.click = function () { downloads.push({ name: this.download, href: this.href }); };
  let lastBlob = null;
  w.URL.createObjectURL = (b) => { lastBlob = b; return 'blob:' + downloads.length; };

  console.log('1) Tema');
  check('começa no tema claro (automático)', doc.documentElement.dataset.theme === 'light' && doc.documentElement.dataset.themePref === 'auto');
  w.toggleTheme(); await tick(20);
  check('alternar vai ao escuro, guarda a escolha e ajusta a cor da barra do navegador', doc.documentElement.dataset.theme === 'dark' && w.localStorage.getItem('minhasplantas_theme') === 'dark' && doc.querySelector('meta[name="theme-color"]').content === '#10170f');
  check('botões de tema mostram o ícone e o rótulo certos', [...doc.querySelectorAll('[data-theme-toggle]')].every(b => b.textContent === '☀️' && /claro/.test(b.getAttribute('aria-label'))));
  check('animação suave de troca é aplicada e removida', true);
  w.setTheme('light'); await tick(20);
  check('claro de novo', doc.documentElement.dataset.theme === 'light' && doc.querySelector('meta[name="theme-color"]').content === '#2f4a2c');
  w.matchMedia = (q) => ({ matches: /dark/.test(q), media: q, addEventListener() {}, removeEventListener() {} });
  w.setTheme('auto'); await tick(20);
  check('automático segue o sistema (escuro)', doc.documentElement.dataset.theme === 'dark' && doc.documentElement.dataset.themePref === 'auto');
  w.matchMedia = (q) => ({ matches: false, media: q, addEventListener() {}, removeEventListener() {} });
  w.setTheme('auto');

  console.log('2) Configurações');
  await w.openSettings(); await tick(60);
  check('painel abre com nome, e-mail e inicial', g('drawerSettings').classList.contains('active') && /Ana Lima/.test(g('drawerSettings').textContent) && /ana@example.com/.test(g('drawerSettings').textContent));
  check('botões de tema com aria-pressed (automático marcado)', doc.querySelector('[data-theme-set="auto"]').getAttribute('aria-pressed') === 'true' && doc.querySelector('[data-theme-set="dark"]').getAttribute('aria-pressed') === 'false');
  w.chooseTheme('dark'); await tick(10);
  check('escolher "Escuro" atualiza o app e o botão', doc.documentElement.dataset.theme === 'dark' && doc.querySelector('[data-theme-set="dark"]').getAttribute('aria-pressed') === 'true');
  w.chooseTheme('auto');
  check('Cloudinary: aviso de que não está configurado', /não configurado/.test(g('cloudStatus').textContent) && g('btnMigratePhotos').hidden);
  check('notificações: sem suporte neste navegador de teste, explica', /não suporta/.test(g('pushBox').textContent), g('pushBox').textContent.slice(0, 80));
  w.closeActiveDrawer();

  console.log('3) Backup e restauração');
  w.exportBackup(); await tick(20);
  const dump = JSON.parse(await readBlob(w, lastBlob));
  check('arquivo de backup: nome com data, app/versão e todos os dados', /^minhas-plantas-backup-\d{4}-\d{2}-\d{2}\.json$/.test(downloads.at(-1).name) && dump.app === 'minhas-plantas' && dump.version === 2 && dump.species.length === 1 && dump.vases.length === 2);
  check('backup guarda o id e não leva o ownerId', dump.species[0].id === 's1' && !('ownerId' in dump.species[0]) && !('firestoreId' in dump.vases[0]) && dump.vases[0].photoHistory.length === 2);
  const bad = (txt) => { try { w.parseBackup(txt); return null; } catch (e) { return e.message; } };
  check('arquivo inválido: mensagens claras', /ilegível/.test(bad('{nao json')) && /não parece ser um backup/.test(bad('{"app":"outro"}')) && /não parece/.test(bad(JSON.stringify({ app: 'minhas-plantas', species: 1, vases: [] }))));
  const parsed = w.parseBackup(JSON.stringify({ app: 'minhas-plantas', species: [{ id: 'a', name: 'X' }, { name: 'sem id' }], vases: [{ id: 'b', speciesId: 'a' }] }));
  check('itens sem id são ignorados', parsed.species.length === 1 && parsed.vases.length === 1);
  // apaga tudo e restaura
  delete fb.data.species.s1; delete fb.data.vases.v1; fb.fire('species'); fb.fire('vases'); await tick(30);
  const restoring = w.importBackup({ text: async () => JSON.stringify({ ...dump, species: [...dump.species, { id: 'novo', name: 'De outra conta', ownerId: 'u-outra' }] }) });
  await tick(40); g('confirmOk').click(); await restoring; await tick(80);
  check('restaura os itens com os mesmos ids', fb.data.species.s1 && fb.data.species.s1.name === 'Jiboia' && fb.data.vases.v1 && fb.data.vases.v1.photoHistory.length === 2);
  check('tudo restaurado passa a ser da conta atual (ownerId = u1), mesmo se o arquivo dizia outra coisa', fb.data.species.novo.ownerId === 'u1' && fb.data.species.s1.ownerId === 'u1' && fb.data.vases.v1.ownerId === 'u1');
  check('aviso de conclusão', /Backup restaurado/.test(t.toasts()));
  const empty = w.importBackup({ text: async () => JSON.stringify({ app: 'minhas-plantas', species: [], vases: [] }) }); await empty; await tick(20);
  check('backup vazio avisa e não pergunta nada', /vazio/.test(t.toasts()));

  console.log('4) Notificações (cliente)');
  const calls = [];
  const reg = { sub: null, pushManager: { getSubscription: async () => reg.sub, subscribe: async (o) => { reg.opts = o; reg.sub = { endpoint: 'https://fcm.test/xyz', toJSON: () => ({ endpoint: 'https://fcm.test/xyz', keys: { auth: 'AUTH', p256dh: 'P' } }), unsubscribe: async () => { reg.sub = null; reg.unsub = true; return true; } }; return reg.sub; } } };
  Object.defineProperty(w.navigator, 'serviceWorker', { value: { ready: Promise.resolve(reg), register() { return Promise.resolve(); }, addEventListener() {} }, configurable: true });
  w.PushManager = function PushManager() {};
  w.Notification = { permission: 'default', requestPermission: async () => { w.Notification.permission = 'granted'; return 'granted'; } };
  w.fetch = async (url, opts) => { calls.push({ url, body: opts && opts.body ? JSON.parse(opts.body) : null }); return { ok: true, status: 200, json: async () => (/vapid/.test(url) ? { key: 'BEl62iUYgUivxIkv69yViEuiBIa-Ib9-SkvMeAtA3LFgDzkrxZJjSgSnfckjBJuBkr3qBUYIHBQFLXYp5Nksh8U' } : { ok: true }) }; };
  await w.openSettings(); await tick(80);
  check('com Worker configurado e navegador compatível, aparece o interruptor (desligado)', g('pushBox').querySelector('.switch') && g('pushBox').querySelector('.switch').getAttribute('aria-checked') === 'false' && g('pushBox').querySelector('.push-hour').hidden);
  await w.togglePush(g('pushBox').querySelector('.switch')); await tick(80);
  const sub = calls.find(c => /subscribe$/.test(c.url));
  check('ativar: pede permissão, busca a chave VAPID e assina com ela (65 bytes)', calls[0].url === 'https://push.test/vapid-public-key' && reg.opts.userVisibleOnly === true && reg.opts.applicationServerKey.length === 65);
  check('envia ao Worker a assinatura, horário (8h), fuso e o resumo de datas', sub && sub.body.subscription.endpoint === 'https://fcm.test/xyz' && sub.body.hour === 8 && typeof sub.body.tzOffset === 'number' && Array.isArray(sub.body.summary) && sub.body.summary.some(i => i.k === 'water' && i.n === 'Vaso da sala'), JSON.stringify(sub && sub.body).slice(0, 200));
  check('interruptor liga e mostra a escolha do horário', g('pushBox').querySelector('.switch').getAttribute('aria-checked') === 'true' && !g('pushBox').querySelector('.push-hour').hidden);
  calls.length = 0;
  await w.changePushHour('19'); await tick(40);
  check('mudar o horário reenvia a assinatura com 19h', calls[0].url === 'https://push.test/subscribe' && calls[0].body.hour === 19);
  calls.length = 0;
  await w.sendTestPush(); await tick(20);
  check('notificação de teste chama /test com o segredo da assinatura', calls[0].url === 'https://push.test/test' && calls[0].body.auth === 'AUTH' && calls[0].body.endpoint === 'https://fcm.test/xyz');
  calls.length = 0;
  await w.syncSummary(); await tick(20);
  check('sincronizar resumo envia só o resumo (sem fotos)', calls[0] && /summary$/.test(calls[0].url) && !JSON.stringify(calls[0].body).includes('base64'));
  calls.length = 0; await w.syncSummary(); await tick(10);
  check('sem mudanças, não reenvia', calls.length === 0);
  calls.length = 0;
  await w.disablePush(); await tick(40);
  check('desativar: cancela a assinatura no navegador e no Worker', reg.unsub === true && calls.some(c => /unsubscribe$/.test(c.url)));
  w.Notification.requestPermission = async () => 'denied';
  let err = await w.enablePush(8).catch(e => e);
  check('permissão negada: erro claro', /Permissão negada/.test(err.message));
  check('sem erros de script', t.errors.length === 0, t.errors.join('|'));
  process.exit(summary() ? 1 : 0);
})().catch(e => { console.error('FALHA', e); process.exit(2); });
